// Package ocicas implements a content-addressed file-set format stored as
// OCI artifacts: files are cut into content-defined chunks (FastCDC), each
// chunk is zstd-compressed and becomes one OCI blob, and a JSON index maps
// paths to chunk digest lists. Identical chunks across cache entries (or
// across versions of a VM image) share one blob in the registry — the
// registry deduplicates by digest, the chunker makes the digests line up.
//
// EVERYTHING in this file is part of the wire format (algo "fastcdc-v1"):
// the gear table, the masks and the size parameters all determine chunk
// boundaries, hence blob digests. Changing any of them breaks deduplication
// against previously pushed entries — bump the algo version instead.
package ocicas

// FastCDC (Xia et al., 2016) parameters: 1 MiB average chunks keep the
// per-entry descriptor count reasonable (a 2 GiB image ≈ 2000 chunks) while
// deduplicating partial changes inside large files.
const (
	MinChunkSize = 256 << 10
	AvgChunkSize = 1 << 20
	MaxChunkSize = 4 << 20
)

// Normalized chunking masks: a harder mask (more bits) before the average
// point, an easier one after, which concentrates the size distribution
// around AvgChunkSize. With the gear fingerprint, bit j of fp only depends
// on the last j input bytes, so the masks' low bits define the effective
// sliding-window size.
const (
	maskS = (1 << 22) - 1
	maskL = (1 << 18) - 1
)

// gear is the random byte→uint64 table of the gear hash, generated by
// SplitMix64 from a fixed seed so that the table is reproducible from code.
var gear = func() [256]uint64 {
	var t [256]uint64
	s := uint64(0x0ca5_fa57_cdc0_0001)
	for i := range t {
		s += 0x9E3779B97F4A7C15
		z := s
		z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9
		z = (z ^ (z >> 27)) * 0x94D049BB133111EB
		t[i] = z ^ (z >> 31)
	}
	return t
}()

// cut returns the length of the next chunk in data. The caller never passes
// more than MaxChunkSize bytes; a full-length return on a MaxChunkSize
// buffer means "no boundary found, force-cut at the maximum".
func cut(data []byte) int {
	n := len(data)
	if n <= MinChunkSize {
		return n
	}
	normal := min(AvgChunkSize, n)
	var fp uint64
	i := MinChunkSize
	for ; i < normal; i++ {
		fp = (fp << 1) + gear[data[i]]
		if fp&maskS == 0 {
			return i + 1
		}
	}
	for ; i < n; i++ {
		fp = (fp << 1) + gear[data[i]]
		if fp&maskL == 0 {
			return i + 1
		}
	}
	return n
}
